name: run-test
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.17.3'
    - name: yarn install
      run: yarn install
    - name: yarn lint
      run: yarn lint